version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: gas_mileage_log_development
      TZ: Asia/Tokyo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/GasMileageLog
      - node_modules:/app/node_modules:cached
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/gas_mileage_log_development
      TZ: Asia/Tokyo
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub

  chrome:
    image: seleniarm/standalone-chromium:latest
    shm_size: 512m
    ports:
      - "4444:4444"

volumes:
  pgdata:
  bundle_data:
  node_modules:
